apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: gcr.io/steady/steady-services-api
          imagePullPolicy: Always
          name: main
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/steady_production"
            - name: ADMIN_EMAIL
              value: "info@paylo.dev"
            - name: ADMIN_PASSWORD
              value: "development.now"
            - name: JWT_SECRET
              value: "changeme1234"
            - name: APP_DOMAIN
              value: "paylo.dev"
            - name: APP_URL
              value: "https://paylo.dev"
            - name: POSTMARK_FROM
              value: "no-reply@paylo.dev"
            - name: POSTMARK_APIKEY
              value: "abc"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "steady-production-uploads"
          ports:
            - name: http-server
              containerPort: 2300
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
